apiVersion: v1
kind: Namespace
metadata:
  name: movie-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-fe
  namespace: movie-app
  labels:
    app: movie-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: movie-app
  template:
    metadata:
      labels:
        app: movie-app
        name: movie-app
    spec:
      containers:
        - name: movie-ui
          image: carlospleon/frontend:latest
          env:
            - name: BACKEND_URL
              value: "movie-app-be:3000"
            - name: PORT
              value: "3030"
          ports:
            - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: movie-app-fe
  namespace: movie-app
spec:
  type: NodePort
  selector:
    app: movie-app
  ports:
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    - port: 3030
      targetPort: 3030
      # Campo opcional
      # Por defecto y por comodidad, el plano de control de Kubernetes asignará el puerto desde un rango (por defecto: 30000-32767)
      nodePort: 30007