apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app-be
  namespace: movie-app
  labels:
    app: movie-app-be
spec:
  replicas: 2
  selector:
    matchLabels:
      name: movie-app-be
  template:
    metadata:
      labels:
        app: movie-app-be
        name: movie-app-be
    spec:
      containers:
        - name: movie-api
          image: carlospleon/backend:latest
          env:
            - name: APP_PORT
              value: "3000"
            - name: DB_HOST
              value: "db-movie-app.cmfd8deuhu77.us-east-1.rds.amazonaws.com"
            - name: DB_USER
              value: "Admin"
            - name: DB_PASS
              value: "password"
            - name: DB_NAME
              value: "movie_db"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: movie-app-be
  namespace: movie-app
spec:
  type: NodePort
  selector:
    app: movie-app-be
  ports:
    # Por defecto y por comodidad, el `TargetPort` tiene el mismo valor que el campo `port.
    - port: 3000
      targetPort: 3000
      # Campo opcional
      # Por defecto y por comodidad, el plano de control de Kubernetes asignará el puerto desde un rango (por defecto: 30000-32767)
      nodePort: 30000